### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by nilsi** [JohNan/home-assistant-plaato#1]
Hi,

Thanks for this integration!

I wonder if these installation instructions are OK? I can only find the old Plaato Airlook integration and not this one when I search in my home assistant.

And the old Plaato Airlook integration does not seem to work. I copy the URL into my plaato airlook but it does not post any data. I got it working last year but not anymore. Do you know if the old Plaato integration still work?

Thank you!

**Comment by nilsi** [comment]
I managed to install it.

I first added the latest release to custom_components folder, then I removed the old Plaato installation before I restarted the device. Then I found the new Plaato integration when searching for integrations and could get the installation tutorial.

Now I just have to wait for my auth token :)

**Comment by JohNan** [comment]
You are absolutely right, the install instructions are for the built in integration, not the standalone version. I will update the Readme asap. 

The updates that you can find int this version are being processed in a PR in the official repository https://github.com/home-assistant/core/pull/34760
