### ISSUE TITLE
Plaato Keg temperature not being updated

### ISSUE THREAD

**Issue by waltlillyman** [JohNan/home-assistant-plaato#11]
Since one of the recent updates, the temperature of the Plaato Keg isn't being updated except once, at startup. Attached is a photo showing the last five days of temperature readings recorded. The blue line is a Samsung temperature sensor inside the keg fridge. The red and green lines are the Plaato Kegs' temperature readings. The recent hard-vertical changes in temps of those coincide with when I restarted Home Assistant. The Plaato Keg mobile app shows the correct temperature, changing over time. You can use the Plaato Keg token I sent you to see the current values via the API.

<img width="446" alt="Screen Shot 2021-01-23 at 6 29 38 PM" src="https://user-images.githubusercontent.com/19913935/105618079-0d5d3300-5da9-11eb-93c6-50f8928c04e8.png">

**Comment by JohNan** [comment]
@waltlillyman I noticed the same issue. Should be fixed in https://github.com/JohNan/home-assistant-plaato/releases/tag/v1.2.5

Sorry for the inconvenience.
