### ISSUE TITLE
Home Assistant 0.115 replaced UNIT_PERCENTAGE with PERCENTAGE

### ISSUE THREAD

**Issue by waltlillyman** [JohNan/home-assistant-plaato#2]
UNIT_PERCENTAGE was changed to PERCENTAGE in Home Assistant version 0.115.
Error in home assistant log file:
`2020-09-17 16:28:45 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform plaato.sensor: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).`

**Comment by JohNan** [comment]
Thanks for reporting. Should be fixed in https://github.com/JohNan/home-assistant-plaato/releases/tag/v1.0.10
