### ISSUE TITLE
Blank Dialog Boxes During Integration Setup

### ISSUE THREAD

**Issue by Tyfosho** [JohNan/home-assistant-plaato#7]
After adding the plaato folder to custom_components, when I go and add the integration, I get blank dialog boxes during the setup.

I was able to guess and put the name in the first line, select Keg, and then the auth_token in the second dialog, but I don't know what the check-box is.

I am having other issues (I've opened them here), so I'm curious if the others are due to the issues with setup. 

https://imgur.com/a/oSk65vr

**Comment by JohNan** [comment]
This should be resolved in latest release, 1.2.2
